### ISSUE TITLE
Can't using Pool module, program no response.

### ISSUE THREAD

**Issue by kevinpound121** [jreese/aiomultiprocess#10]
### Description
When I using the Pool module the program was stuck without error shows only in Win10(with your sample code). CMD will show some error after a long while.
```
[Error - 1:22:03 PM] Request textDocument/hover failed.
  Message: unknown document
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing)
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(TextDocumentIdentifier document, Nullable`1 expectedVersion, ProjectEntry& entry, PythonAst& tree)
   at Microsoft.Python.LanguageServer.Implementation.Server.Hover(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Hover(JToken token, CancellationToken cancellationToken)
```
But I can run this code in CentOS 6, it seems like only shows in the Window,

I've used debuger to check this error, the code was stuck in base_events.py and the method call run_forever, it looks like an endless loop there 

Here is my code:
```python
import asyncio
import aiohttp
import time
from aiomultiprocess import Pool

async def get(url):
    session = aiohttp.ClientSession()
    response = await session.get(url)
    session.close()
    return response

async def request():
    url = 'https://jreese.sh'
    urls = [url for _ in range(5)]
    async with Pool() as pool:
        result = await pool.map(get, urls)
        return result

coroutine = request()
task = asyncio.ensure_future(coroutine)
loop = asyncio.get_event_loop()
loop.run_until_complete(task)
```

### Details

* OS: Windows10 & CentOS 6
* Python version: Python 3.6.6(Win10), Python3.4(CentOS 6)
* aiomultiprocess version: v0.5.0
* Can you repro on master? 
* Can you repro in a clean virtualenv?

**Comment by kevinpound121** [comment]
thx~
