### ISSUE TITLE
Can not use asyncio.Queue inProcess

### ISSUE THREAD

**Issue by sunhailin-Leo** [jreese/aiomultiprocess#11]
### Details

* OS:
* Python version:
* aiomultiprocess version:
* Can you repro on master?
* Can you repro in a clean virtualenv?

**Comment by sunhailin-Leo** [comment]
How can I use asyncio.Queue in aiomultiprocess? @jreese

**Comment by parinmaru2** [comment]
Hey @jreese First of all amazing library. Just stumbled upon this yesterday, starting playing around and am loving it.

Seeing one issue where I can use your expertise. I am trying to use multiprocessing.queue to share data between different processes. But that's not working for me.

Here is how I am starting aiomultiprocess worker:
```
child_recipe = ChildRecipe() 
q = Queue() # # this is multiprocessing.Queue
p = Worker(target=child_recipe.start,  args=(q,)) ## child_recipe.start is the coroutine I am invoking on different process
```

And in my child_recipe.start() coroutine, I am trying to put data in this queue:
```
    async def start(self, q):
        q.put([42, None, 'hello'])
```
And this q.put() is throwing me error: `OSError: [Errno 9] Bad file descriptor`

The full stack trace is:
```
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pmaru/Desktop/src/useful_tools-pmaru-master/useful_tools/venv/lib/python3.6/site-packages/aiomultiprocess/core.py", line 217, in run_async
    result: R = Process.run_async(unit)
  File "/Users/pmaru/Desktop/src/useful_tools-pmaru-master/useful_tools/venv/lib/python3.6/site-packages/aiomultiprocess/core.py", line 136, in run_async
    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/Users/pmaru/Desktop/src/useful_tools-pmaru-master/useful_tools/recipe_execution/aiomultiprocess/aiomultiprocess2.py", line 78, in start
    q.put([42, None, 'hello'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/queues.py", line 82, in put
    if not self._sem.acquire(block, timeout):
OSError: [Errno 9] Bad file descriptor
```

I am sure I am missing something silly here. But would really appreciate your help here.
I am guessing sharing data using multiprocess.queue is supported by this library.

Thanks in advance, Parin

**Comment by jreese** [comment]
You might need to use the "manager" object from aiomultiprocess to get appropriately-shared queues. Something like `queue = aiomultiprocess.get_manager().Queue()`

**Comment by parinmaru2** [comment]
Great. will check it out @jreese 
Thanks for your quick response.

**Comment by alexwbai** [comment]
Hey @jreese first off this project is great... initially my code was taking 40 seconds to run against one device, now I can do 5 devices in parallel in 3-5 seconds!  Thanks for putting in the time making this.

Quick question though-

I was hoping you could give a quick example when you mention this:
`Something like queue = aiomultiprocess.get_manager().Queue()`

I'm trying to find ways of creating an object in a parent process and then passing that object to a child process (or creating it in the child process and passing it up to the parent) but like the OP, I am getting pickling errors.  I'm hoping that the get_manager().Queue() is the way to go but am just a little stuck.  In my case the data structure in the Queue would be a list with dictionaries ie. [ {key: myObject}, {key: myObject} ]

**Comment by jreese** [comment]
Pickling errors usually implies that the objects you are attempting to pass are using types that were generated at runtime rather than at import time. Eg, if you have a class or function that is defined inside of another function, those aren't directly attached to a module that can be imported in the parent or child process, and therefore can't be pickled because the receiving end doesn't have the type information to use them. In these cases, you need to move the class or function definition into the global scope, or manually serialize the objects into standard types before passing them between processes.

**Comment by karolzlot** [comment]
I tried to use `multiprocessing.Queue` inside aiomultiprocess by passing it through `initializer`, hoever when I use it inside `run_one_job` method it crashes whole process.

This is complete code, you can run it "as-is":
```python
import asyncio
from typing import Any
from multiprocessing import Queue
from aiomultiprocess import Pool

_queue: Any

def _init_worker(queue):
    global _queue
    _queue = queue

async def run_one_job(job):
    print("starting job...")
    _queue.put(job) # this crashes processes
    return job # this line is never reached

async def main():
            
    print(f"Starting queue process")
    queue = Queue()

    jobs=list(range(100))

    async with Pool(
        initializer=_init_worker,
        initargs=(queue,),
        processes=2,
        childconcurrency=2,
        ) as pool:

        async for result in pool.map(run_one_job, jobs):
            print(result)
            pass

if __name__ == "__main__":
    asyncio.run(main())
```

How to make it work?

Alternatively how `get_manager()` can be used to make it work?

**Comment by jreese** [comment]
Try using `queue = aiomultiprocess.core.get_manager().Queue()`.

**Comment by karolzlot** [comment]
Wow, it is working!

Here is complete working code:
```python
import asyncio
from typing import Any
from aiomultiprocess import Pool
from aiomultiprocess.core import get_manager

_queue: Any 

def _init_worker(queue):
    global _queue
    _queue = queue

async def run_one_job(job):
    print("starting job...")
    _queue.put(job)
    return job

async def main():
            
    print(f"Starting queue process")
    queue = get_manager().Queue()

    jobs=list(range(40))

    async with Pool(
        initializer=_init_worker,
        initargs=(queue,),
        processes=10,
        childconcurrency=10,
        ) as pool:

        async for result in pool.map(run_one_job, jobs):
            print(result)

if __name__ == "__main__":
    asyncio.run(main())
```
