### ISSUE TITLE
example for server side

### ISSUE THREAD

**Issue by drv1234** [jreese/aiomultiprocess#16]
### Description
hi,
could you please provide a simple example for server side based on this example:
https://docs.python.org/3/library/asyncio-stream.html#tcp-echo-server-using-streams

### Details
I tried but I got this:

RuntimeError: Task <Task pending coro=<handle_echo() running at server0.py:15> cb=[_run_until_complete_cb() at /usr/local/lib/python3.7/asyncio/base_events.py:158]> got Future <Future pending> attached to a different loop

on windows nothing happend

* OS: linux/windows
* Python version: 3.7.2
* aiomultiprocess version: 0.5.0
* Can you repro on master?
* Can you repro in a clean virtualenv?

**Comment by drv1234** [comment]
one more thing which maybe was not clear from my previous post: I would like to start new process for every new client-server connection

thansk

**Comment by jreese** [comment]
a) I would suggest using a process pool instead of creating a new process for each connection.  This will save you the expense of process creation on each individual request, and will also prevent out-of-memory errors or the creation of too many processes when a flood of requests come in.

b) you most likely need to add some amount of "plumbing" to pass request data from the parent process to the child for each request.  When using a process pool, you can use the `apply()` method to execute a coroutine with some parameters on the next available child process.  Something like this:

```python
pool = aiomultiprocess.Pool()

async def child_handler(message: str) -> str:
    return message  # process input data here

async def parent_handler(reader, writer):
    data = await reader.read()
    message = data.decode()

    result = await Pool.apply(child_handler, args=(message, ))
    writer.write(result)
    await writer.drain()
    writer.close()

async def main():
    server = await asyncio.start_server(
        parent_handler, '127.0.0.1', 8888)

   async with server:
        await server.serve_forever()
```

**Comment by littleningmeng** [comment]
> a) I would suggest using a process pool instead of creating a new process for each connection. This will save you the expense of process creation on each individual request, and will also prevent out-of-memory errors or the creation of too many processes when a flood of requests come in.
> 
> b) you most likely need to add some amount of "plumbing" to pass request data from the parent process to the child for each request. When using a process pool, you can use the `apply()` method to execute a coroutine with some parameters on the next available child process. Something like this:
> 
> ```python
> pool = aiomultiprocess.Pool()
> 
> async def child_handler(message: str) -> str:
>     return message  # process input data here
> 
> async def parent_handler(reader, writer):
>     data = await reader.read()
>     message = data.decode()
> 
>     result = await Pool.apply(child_handler, args=(message, ))
>     writer.write(result)
>     await writer.drain()
>     writer.close()
> 
> async def main():
>     server = await asyncio.start_server(
>         parent_handler, '127.0.0.1', 8888)
> 
>    async with server:
>         await server.serve_forever()
> ```

I got an error when using the demo code  
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/qspace/python3.8.2/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/qspace/python3.8.2/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/qspace/python3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/qspace/ss.py", line 6, in <module>
    pool = aiomultiprocess.Pool()
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 186, in __init__
    self.init()
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 214, in init
    self.processes[self.create_worker(qid)] = qid
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 251, in create_worker
    process = PoolWorker(
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 59, in __init__
    super().__init__(
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/core.py", line 109, in __init__
    namespace=get_manager().Namespace(),
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/core.py", line 29, in get_manager
    _manager = context.Manager()
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "ss.py", line 6, in <module>
    pool = aiomultiprocess.Pool()
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 186, in __init__
    self.init()
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 214, in init
    self.processes[self.create_worker(qid)] = qid
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 251, in create_worker
    process = PoolWorker(
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 59, in __init__
    super().__init__(
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/core.py", line 109, in __init__
    namespace=get_manager().Namespace(),
  File "/home/qspace/python3.8.2/lib/python3.8/site-packages/aiomultiprocess/core.py", line 29, in get_manager
    _manager = context.Manager()
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/qspace/python3.8.2/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFErro
```
