### ISSUE TITLE
Problem when using aiomultiprocess with aiopipe

### ISSUE THREAD

**Issue by momocow** [jreese/aiomultiprocess#40]
### Description
Hi, I'm trying to combine `aiomultiprocess` with [`aiopipe`](https://github.com/kchmck/aiopipe), which in its demo shows that it works well with `multiprocessing.Process` (and indeed it works well with `multiprocessing` since I've tried it).

I've modified aiopipe's duplex pipe demo into the snippet as below. The only difference is that I changed `multiprocessing.Process` to `aiomultiprocess.Process` and made it awaiting on `proc.join()` instead of a blocking call. And the `asyncio.run` part is also removed since it's no longer needed in `aiomultiprocess`.

Here is my snippet:
```py
# test.py

import asyncio
from aiomultiprocess import Process
from aiopipe import aioduplex

async def test(ipc):
    async with ipc.open() as (rx, tx):
        tx.write(b"hello")
        rep = await rx.readline()
        tx.write(rep.upper())

async def main():
    mainpipe, chpipe = aioduplex()
    with chpipe.detach() as chpipe:
        proc = Process(target=test, args=(chpipe,))
        proc.start()

    async with mainpipe.open() as (rx, tx):
        req = await rx.read(5)
        tx.write(req + b" world\n")
        msg = await rx.readline()
    
    await proc.join()
    print(msg)

if __name__ == "__main__":
    asyncio.run(main())
```

But it failed with the `Bad file descriptor` error.
```
aio process 18680 failed
Traceback (most recent call last):
  File "<project_dir>/venv/lib/python3.7/site-packages/aiomultiprocess/core.py", line 132, in run_async
    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "<project_dir>/test.py", line 10, in test
    async with ipc.open() as (rx, tx):
  File "/usr/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "<project_dir>/venv/lib/python3.7/site-packages/aiopipe/__init__.py", line 267, in open
    async with self._rx.open() as rx, self._tx.open() as tx:
  File "/usr/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "<project_dir>/venv/lib/python3.7/site-packages/aiopipe/__init__.py", line 133, in open
    transport, stream = await self._open()
  File "<project_dir>/venv/lib/python3.7/site-packages/aiopipe/__init__.py", line 196, in _open
    os.fdopen(self._fd))
  File "/usr/lib/python3.7/os.py", line 1026, in fdopen
    return io.open(fd, *args, **kwargs)
OSError: [Errno 9] Bad file descriptor
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "<project_dir>/venv/lib/python3.7/site-packages/aiomultiprocess/core.py", line 132, in run_async
    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "<project_dir>/test.py", line 10, in test
    async with ipc.open() as (rx, tx):
  File "/usr/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "<project_dir>/venv/lib/python3.7/site-packages/aiopipe/__init__.py", line 267, in open
    async with self._rx.open() as rx, self._tx.open() as tx:
  File "/usr/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "<project_dir>/venv/lib/python3.7/site-packages/aiopipe/__init__.py", line 133, in open
    transport, stream = await self._open()
  File "<project_dir>/venv/lib/python3.7/site-packages/aiopipe/__init__.py", line 196, in _open
    os.fdopen(self._fd))
  File "/usr/lib/python3.7/os.py", line 1026, in fdopen
    return io.open(fd, *args, **kwargs)
OSError: [Errno 9] Bad file descriptor

```

The error was raised **from the child process** when it tried to open the pipes at the line `ipc.open()` in function `test`. In the backtrace it shows that `self._fd` is a bad file descriptor which is obtained from `os.pipe()`. ([source](https://github.com/kchmck/aiopipe/blob/662eabf25b01d22811cbe7c9abee77b4170f3ab8/aiopipe/__init__.py#L105-L106))
```py
def aiopipe() -> Tuple["AioPipeReader", "AioPipeWriter"]:
    rx, tx = os.pipe()
    return AioPipeReader(rx), AioPipeWriter(tx)
```

I've dug a little bit into both `aiomultiprocess` and `aiopipe`, both of which are not in large code base therefore it's not a pain to do code tracing.

I see  `aiomultiprocess` use `multiprocessing.Process` under the hood (did I misunderstand anything?).
https://github.com/jreese/aiomultiprocess/blob/aa623804a668ee2d6cd0a8b56a630d1e9bdaef78/aiomultiprocess/core.py#L107-L113

Since `aiopipe` plays well with `multiprocessing` but not `aiomultiprocess`, I need some helps to figure out what I mistook and when and why was the file descriptor corrupted.

Thanks for the great library anyway!

### Details

* OS: Ubuntu 16.04
* Python version: 3.7.3
* aiomultiprocess version: 0.7.0
* Can you repro on master? Not sure, have not tried yet.
* Can you repro in a clean virtualenv? Yes, only `aiomultiprocess` and `aiopipe` are installed.
```
(venv) $ pip freeze
aiomultiprocess==0.7.0
aiopipe==0.2.2
```

**Comment by bouillon** [comment]
I confirm the same here with Python 3.8.2rc1 (default, Feb 11 2020, 15:26:48)

**Comment by bouillon** [comment]
Ok, your code will work if you put

```
import aiomultiprocess
aiomultiprocess.set_start_method('fork')
```
somewhere

**Comment by momocow** [comment]
@bouillon Nice, thank you very much!

The file descriptor is broken since the default start method is set to `spawn` here, set it to `fork` resolve the issue.

https://github.com/jreese/aiomultiprocess/blob/6234e9e935be3096a4339619047ea9287124f977/aiomultiprocess/core.py#L14
